export default {
  h1: {
    fontFamily: 'Barlow Condensed',
    fontWeight: 300,
    fontSize: '85px',
    lineHeight: '90px',
    letterSpacing: '-1.5px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  h2: {
    fontFamily: 'Barlow Condensed',
    fontWeight: 400,
    fontSize: '60px',
    lineHeight: '69px',
    letterSpacing: '-0.5px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  h3: {
    fontFamily: 'Barlow Condensed',
    fontWeight: 500,
    fontSize: '50px',
    lineHeight: '56px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  h4: {
    fontFamily: 'Barlow Condensed',
    fontWeight: 400,
    fontSize: '35px',
    lineHeight: '36px',
    letterSpacing: '0.25px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  h5: {
    fontFamily: 'Barlow Condensed',
    fontWeight: 500,
    fontSize: '30px',
    lineHeight: '35px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  h6: {
    fontFamily: 'Barlow Condensed',
    fontWeight: 400,
    fontSize: '21px',
    lineHeight: '25px',
    letterSpacing: '0.15px',
    color: 'rgba(0, 0, 0, 0.87)',
  },

  body1: {
    fontFamily: 'Barlow',
    fontWeight: 400,
    fontSize: '17px',
    lineHeight: '22px',
    letterSpacing: '0.5px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  body2: {
    fontFamily: 'Barlow',
    fontWeight: 400,
    fontSize: '15px',
    lineHeight: '20px',
    letterSpacing: '0.25px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  button: {
    fontFamily: 'Barlow',
    fontWeight: 600,
    fontSize: '15px',
    lineHeight: '18px',
    letterSpacing: '1.25px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  caption: {
    fontFamily: 'Barlow',
    fontWeight: 400,
    fontSize: '13px',
    lineHeight: '16px',
    letterSpacing: '0.4px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  overline: {
    fontFamily: 'Barlow',
    fontWeight: 500,
    fontSize: '10px',
    lineHeight: '15px',
    letterSpacing: '1.5px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
};
